import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Header from "../components/layout/header";
const inter = Inter({ subsets: ["latin"] });

const gtSuper = localFont({
  src: "./fonts/gt-super/GT-Super-Display-Light.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gtSuper.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
